# Generated by Django 3.2.3 on 2021-06-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210530_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': ('категория',), 'verbose_name_plural': 'категории'},
        ),
    ]
