# Generated by Django 3.2.3 on 2021-08-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210615_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='updated',
        ),
        migrations.AddField(
            model_name='product',
            name='image_preview_1',
            field=models.ImageField(blank=True, upload_to='products_images', verbose_name='дополнительное изображение 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_preview_2',
            field=models.ImageField(blank=True, upload_to='products_images', verbose_name='дополнительное изображение 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_preview_3',
            field=models.ImageField(blank=True, upload_to='products_images', verbose_name='дополнительное изображение 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активный'),
        ),
        migrations.AddField(
            model_name='product',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images', verbose_name='изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, max_length=256, verbose_name='краткое описание'),
        ),
    ]
