# Generated by Django 3.2.3 on 2021-08-18 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='language',
            field=models.CharField(blank=True, max_length=20, verbose_name='язык'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='url_vk',
            field=models.CharField(blank=True, max_length=100, verbose_name='ссылка вк контакты'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 16, 36, 16, 656181)),
        ),
    ]
